### ISSUE TITLE
check_mssql_database.py Caught unexpected error

### ISSUE THREAD

**Issue by rchekaluk** [NagiosEnterprises/check_mssql_collection#2] opened 2014-08-12 18:47 UTC
Receive the following error on Ubuntu 14.04, Python 2.7.6 

```
<type 'exceptions.TypeError'>
Caught unexpected error. This could be caused by your sysperfinfo not containing the proper entries for this query, and you may delete this service check.
```

After commenting out the final 4 lines of check_mssql_database.py, the exception is:

```
$ /tmp/check_mssql_database.py --hostname=$host --user=$dbuser --password=$dbpswd --table=dbadmin --datasize
Traceback (most recent call last):
  File "/tmp/check_mssql_database.py", line 352, in <module>
    main()
  File "/tmp/check_mssql_database.py", line 318, in main
    execute_query(mssql, options, host)
  File "/tmp/check_mssql_database.py", line 331, in execute_query
    mssql_query.do(mssql)
  File "/tmp/check_mssql_database.py", line 167, in do
    self.run_on_connection(connection)
  File "/tmp/check_mssql_database.py", line 154, in run_on_connection
    self.query_result = cur.fetchone()[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

The solution mentioned in https://github.com/NagiosEnterprises/check_mssql_collection/issues/1#issuecomment-51666680 does not help, even after installing cython:

```
$ pip freeze | egrep -i pymssql\|cython
Cython==0.20.2
pymssql==2.1.0
```

**Comment by hedenface** [comment] 2017-06-17 02:00
I'm closing this since this issue is ~3 years old. @rchekaluk if you're still having this issue, please re-open the issue or inform me and we will try and get it resolved!

**Closed by hedenface** 2017-06-17 02:00 UTC

**Comment by curtbay** [comment] 2017-12-11 16:35
Hi, 
I have the same problem and I don't know how to fix it. 
Can you help me please ? 
I have this error when I do my check : 
<type 'exceptions.TypeError'>
Caught unexpected error. This could be caused by your sysperfinfo not containing the proper entries for this query, and you may delete this service check.

Thank you
Bests Regards

**Comment by jomann09** [comment] 2017-12-11 16:52
What version of MSSQL are you checking again?

**Comment by curtbay** [comment] 2017-12-11 18:59
Sorry , I did'nt say it. 
It's MSSQL express 2016. 
Thank you for your help.

**Comment by jomann09** [comment] 2017-12-11 19:25
I didn't think it was an issue with 2016, but would you be able to change line 38-39 in your plugin to use `sys.dm_os_performance_counters` instead of `sys.sysperfinfo` and try it, and let me know if you get results instead of an empty counter?

**Comment by curtbay** [comment] 2017-12-11 19:56
Ok , I think I'm able change line 38-39 to use sys.dm_os_performance_counters. I will try it tomorrow morning because I don't have access to the server now. I will let you know the result. 
Thank you.

**Comment by curtbay** [comment] 2017-12-12 09:04
Hi, 
I changed lines 38-39 but I have the same error message : 
<type 'exceptions.TypeError'>
Caught unexpected error. This could be caused by your sysperfinfo not containing the proper entries for this query, and you may delete this service check.

Thanks.
